const around = [
    {
        path: "art-culture",
        title: "Art & Culture",
        description: "",
        img: "/Bed.png",
        content: [
            {
                title: "Leiria Castle",
                text: "Leiria Castle, perched on a hilltop, offers stunning panoramic views of the city and surrounding landscapes. Originally built in the 12th century, this historic fortress was expanded over the centuries, showcasing a mix of Romanesque, Gothic, and Manueline architectural styles. It has witnessed significant events in Portuguese history, and today, it hosts various cultural activities, including historical reenactments, exhibitions, and concerts. The castle's central location makes it a must-visit landmark in Leiria, providing visitors with a glimpse into the past while enjoying breathtaking views.",
                image: "/Bed.png",
                address: "Rua do Castelo, 2400-235 Leiria",
                website: "https://www.visiteleiria.pt",
            },
            {
                title: "José Malhoa Museum",
                text: "Located in Caldas da Rainha, the José Malhoa Museum is dedicated to the life and works of one of Portugal's most influential artists, José Malhoa. This museum showcases a vast collection of Malhoa's paintings, with a particular emphasis on his famous works that depict rural life and landscapes. The museum also features pieces by other Portuguese artists from the 19th and 20th centuries, offering an insight into the development of Portuguese art during these periods. The building itself is an architectural gem, adding to the museum's cultural significance in the region.",
                image: "/Bed.png",
                address: "Parque D. Carlos I, 2500-109 Caldas da Rainha",
                website: "http://mjm.imc-ip.pt",
            },
            {
                title: "Marinha Grande Glass Museum",
                text: "The Marinha Grande Glass Museum offers a fascinating journey through the history of glassmaking in the region, which has been renowned for its glass production for centuries. The museum showcases a wide array of glass objects, from delicate decorative pieces to functional items, reflecting the craftsmanship and skill of local artisans. Visitors can learn about traditional glassmaking techniques, watch live demonstrations, and explore exhibits that highlight the role of glass in both local and international contexts. The museum is an essential stop for anyone interested in the art and history of glassmaking.",
                image: "/Bed.png",
                address: "Rua 1º de Maio, 2430-184 Marinha Grande",
                website: "http://www.museudovidro.pt",
            },
            {
                title: "MCCB - Batalha Municipality Community Museum",
                text: "Located near the Batalha Monastery, a UNESCO World Heritage site, the MCCB (Municipal Community Museum) offers a comprehensive look at the history and culture of the Batalha region. The museum features exhibits that explore local traditions, agricultural practices, and the evolution of the community from medieval times to the present. The museum’s location, close to the historic monastery, allows it to incorporate themes related to religion, history, and the famous Battle of Aljubarrota. It also regularly hosts temporary exhibitions and cultural events.",
                image: "/Bed.png",
                address: "Largo Goa, Damão e Diu, 2440-901 Batalha",
                website: "http://www.museubatalha.com",
            },
            {
                title: "Leiria Museum",
                text: "The Leiria Museum is an integral part of the city's cultural landscape, housed in the former convent of Santo Agostinho. The museum’s collection spans a wide range of periods and subjects, from archaeological finds to contemporary art. The museum is particularly renowned for its archaeological collection, which includes important prehistoric and Roman artifacts discovered in the region. Additionally, it hosts temporary exhibitions, cultural events, and educational workshops, making it an excellent resource for anyone interested in the history and culture of Leiria.",
                image: "/Bed.png",
                address: "Rua Tenente Valadim, 41, 2410-190 Leiria",
                website: "https://www.cm-leiria.pt/pages/849",
            },
            {
                title: "Santuário de Nossa Senhora da Nazaré",
                text: "The Sanctuary of Our Lady of Nazaré is one of Portugal’s most famous pilgrimage sites, deeply embedded in both the religious and cultural life of the region. The sanctuary is home to the venerated image of Our Lady of Nazaré, which has been the center of devotion for centuries. The church itself is an architectural masterpiece, with elements dating back to the 14th century. The sanctuary is surrounded by a vibrant cultural atmosphere, with various religious celebrations and cultural events throughout the year, including the famous Nossa Senhora da Nazaré pilgrimage.",
                image: "/Bed.png",
                address: "Praça Sousa Oliveira, 2450-065 Nazaré",
                website: "http://www.santuarionazare.pt",
            },
            {
                title: "José Saramago House Museum",
                text: "The José Saramago House Museum, located in the author’s childhood home, is dedicated to the life and literary works of the Nobel Prize-winning writer. The museum offers visitors a unique insight into Saramago's personal life, showcasing his early writings, manuscripts, and personal belongings. Visitors can also explore a library containing a vast collection of his works and other literary treasures. The museum offers a contemplative atmosphere, reflecting the themes of memory and reflection that were central to Saramago's writings.",
                image: "/Bed.png",
                address: "Rua José Saramago, 2440-137 Azinhaga",
                website: "http://www.museujosesaramago.pt",
            },
            {
                title: "Caldas da Rainha Contemporary Art Museum",
                text: "This contemporary art museum is a cultural hub in Caldas da Rainha, showcasing a range of modern artistic expressions, from painting and sculpture to multimedia art. The museum hosts rotating exhibitions featuring both national and international artists, offering a dynamic space for contemporary art in the region. It also organizes educational programs, workshops, and events that engage the local community and visitors alike. With its vibrant exhibitions and welcoming atmosphere, the museum plays a key role in promoting the arts and fostering creativity in the area.",
                image: "/Bed.png",
                address: "Parque D. Carlos I, 2500-109 Caldas da Rainha",
                website: "http://www.mccr.com",
            },
            {
                title: "Alcobaça Monastery",
                text: "The Alcobaça Monastery is a magnificent example of Gothic architecture in Portugal, founded in 1153 and a UNESCO World Heritage site. The monastery is famous for its stunning architecture, vast cloisters, and the tombs of King Pedro I and his lover Inês de Castro. The monastery houses important historical artifacts, including a remarkable collection of medieval manuscripts and religious relics. Visitors can explore the monastery’s beautiful surroundings, including the peaceful gardens, while learning about its historical significance as a center of religious and cultural life.",
                image: "/Bed.png",
                address: "Largo do Mosteiro, 2460-018 Alcobaça",
                website: "https://www.mosteiroalcobaca.gov.pt",
            },
            {
                title: "Museu do Chocolate - Óbidos",
                text: "Located in the charming medieval town of Óbidos, the Chocolate Museum is a delightful celebration of Portugal's chocolate history. The museum offers a hands-on experience where visitors can learn about the origins of chocolate, its production process, and its cultural significance in Portuguese traditions. It features a wide variety of exhibits, from historical chocolate-making tools to contemporary chocolate sculptures. Visitors can also enjoy chocolate tastings and learn how to create their own delicious chocolate treats in workshops.",
                image: "/Bed.png",
                address: "Rua Direita, 2510-001 Óbidos",
                website: "http://www.museudochocolate.pt",
            },
            {
                title: "Óbidos Castle",
                text: "Óbidos Castle is a stunning medieval fortress, offering an excellent opportunity to explore Portugal’s rich history. Originally built in the 12th century, the castle has been beautifully preserved and features traditional architectural elements, including fortified walls and a central keep. Today, the castle is open to the public and offers a fascinating journey through Portugal's medieval past. Visitors can wander through its rooms, climb its towers for panoramic views, and enjoy the picturesque surroundings of the town, which is renowned for its cobbled streets and whitewashed houses.",
                image: "/Bed.png",
                address: "Rua do Castelo, 2510-999 Óbidos",
                website: "https://www.obidos.pt/en/castle",
            },
            {
                title: "Museu da Comunidade de Fátima",
                text: "The Fátima Community Museum provides a comprehensive look into the cultural and religious significance of the Fátima sanctuary. The museum’s exhibits explore the history of the Marian apparitions that took place in 1917, as well as the subsequent global devotion to Our Lady of Fátima. The museum also showcases the development of Fátima as a pilgrimage site, with artifacts, photographs, and stories from devotees around the world. Visitors can learn about the religious, cultural, and social impact of Fátima on Portugal and beyond.",
                image: "/Bed.png",
                address: "Rua Jacinta Marto, 2495-400 Fátima",
                website: "http://www.mcf.pt",
            },
            {
                title: "Cultural Center of Caldas da Rainha",
                text: "The Cultural Center of Caldas da Rainha is a dynamic venue for artistic and cultural activities, offering a variety of exhibitions, performances, and workshops. The center is a focal point for the promotion of local culture and the arts, hosting events that range from art exhibitions and theater productions to live music and dance performances. It is an ideal place for visitors to experience contemporary and traditional Portuguese culture in a relaxed and engaging environment.",
                image: "/Bed.png",
                address: "Avenida 1º de Maio, 2500-231 Caldas da Rainha",
                website: "http://www.culturalcaldas.pt",
            },
        ],
    },
    {
        path: "beaches",
        title: "Beaches",
        description: "",
        img: "/Bed.png",
        content: [
            {
                title: "Nazaré Beach",
                text: "Nazaré Beach is world-renowned for its gigantic waves and dramatic coastline. Popular among surfers and tourists alike, it offers a vibrant promenade, traditional fishing boats, and stunning views from the cliffs of Sítio. During the winter, it attracts professional surfers who come to challenge some of the biggest surfable waves on the planet.",
                image: "/Bed.png",
                address: "Avenida da República, 2450-101 Nazaré",
            },
            {
                title: "São Martinho do Porto Beach",
                text: "Located in a naturally sheltered bay, São Martinho do Porto Beach is ideal for families and calm-water swimming. The beach features a charming village atmosphere with restaurants and cafes lining the shore. Its crescent-shaped bay is unique in Portugal and perfect for a relaxing beach day.",
                image: "/Bed.png",
                address: "Avenida Marginal, 2460-096 São Martinho do Porto",
            },
            {
                title: "Foz do Arelho Beach",
                text: "Foz do Arelho Beach is known for its dual personality: a calm lagoon ideal for paddleboarding and families, and the wild Atlantic side favored by surfers. This scenic spot also offers wooden walkways, beach bars, and plenty of space for sunbathing and walks along the coast.",
                image: "/Bed.png",
                address: "Avenida do Mar, 2500-500 Foz do Arelho",
            },
            {
                title: "Vieira Beach",
                text: "Praia da Vieira is a wide sandy beach bordered by a pine forest and a vibrant seaside town. It offers a mix of traditional fishing culture and modern beach facilities, including restaurants, bars, and summer events. The beach is also known for its colorful fishing boats and fresh seafood.",
                image: "/Bed.png",
                address: "Avenida Marginal, 2430-696 Vieira de Leiria",
            },
            {
                title: "Pedrógão Beach",
                text: "Pedrógão Beach offers a laid-back and less crowded atmosphere compared to nearby coastal towns. Surrounded by dunes and pine forests, it is ideal for those seeking a quieter, more natural beach experience. Local restaurants serve fresh fish, and the area is perfect for long beach walks.",
                image: "/Bed.png",
                address: "Avenida da Praia, 2425-449 Praia do Pedrógão",
            },
            {
                title: "Paredes da Vitória Beach",
                text: "Paredes da Vitória Beach is a stunning and spacious beach, perfect for families and surfers. With cliffs and green hills framing the golden sands, it is a great spot for sunbathing, swimming, and exploring natural rock formations. The surrounding village offers several cafes and local shops.",
                image: "/Bed.png",
                address: "Rua da Praia, 2450-138 Paredes da Vitória",
            },
            {
                title: "Vale Furado Beach",
                text: "Tucked beneath golden cliffs and surrounded by nature, Vale Furado Beach is a hidden gem. Accessible via a steep path, this secluded beach offers tranquility, impressive rock formations, and a peaceful retreat from the more touristy spots. Ideal for photography and peaceful contemplation.",
                image: "/Bed.png",
                address: "Estrada Vale Furado, 2445-017 Alcobaça",
            },
            {
                title: "Agua de Madeiros Beach",
                text: "Agua de Madeiros Beach is known for its dramatic cliffs and natural surroundings. It’s a quiet beach ideal for long walks, photography, and enjoying nature. Due to strong currents and rocks, it is not recommended for swimming, but it offers a spectacular coastal experience.",
                image: "/Bed.png",
                address: "Rua da Praia, Água de Madeiros, 2445-505 Alcobaça",
            },
            {
                title: "Polvoeira Beach",
                text: "Polvoeira Beach is a wild and scenic beach surrounded by cliffs, ideal for those looking for peace and unspoiled nature. There are no major tourist facilities here, which keeps the environment natural and pristine. The ocean here can be rough, making it more suitable for experienced swimmers.",
                image: "/Bed.png",
                address: "Rua da Polvoeira, 2445-505 Alcobaça",
            },
            {
                title: "Falca Beach",
                text: "Falca Beach is a small and quiet beach nestled between cliffs, popular with locals seeking a peaceful and less crowded alternative. Its golden sands and clear waters make it a great spot for sunbathing and relaxation. The natural beauty of the surrounding cliffs enhances its charm.",
                image: "/Bed.png",
                address: "Rua da Falca, 2445-505 São Martinho do Porto",
            },
        ],
    },
    {
        path: "restaurants",
        title: "Restaurants",
        description: "",
        img: "/Bed.png",
        content: [
            {
                title: "Varanda do Casal",
                text: "Nestled at the entrance of the Schist Village of Casal de São Simão, Varanda do Casal offers traditional Portuguese cuisine with a stunning panoramic view. The rustic ambiance complements dishes like 'bacalhau à lagareiro' and 'cabrito assado'.",
                image: "/Bed.png",
                address: "Casal de São Simão, 3260-034 Figueiró dos Vinhos",
            },
            {
                title: "O Celeiro",
                text: "Located in Reguengo do Fetal, O Celeiro is a family-run restaurant serving authentic Portuguese dishes in a cozy setting. Specialties include grilled meats and regional desserts.",
                image: "/Bed.png",
                address: "EN356, 572, Reguengo do Fetal, 2440-000 Batalha",
            },
            {
                title: "Marisqueira Mirandum",
                text: "Situated in Pombal, Marisqueira Mirandum is renowned for its fresh seafood offerings. The menu features a variety of shellfish dishes, including 'ameijoas à Bulhão Pato' and grilled tiger prawns.",
                image: "/Bed.png",
                address: "Rua de Leiria 85, 3100-480 Pombal",
            },
            {
                title: "O Caçador",
                text: "In the heart of Figueiró dos Vinhos, O Caçador offers traditional Portuguese cuisine with a focus on game meats. The rustic decor and hearty dishes provide a warm dining experience.",
                image: "/Bed.png",
                address:
                    "Rua Major Neutel de Abreu 133, 3260-427 Figueiró dos Vinhos",
            },
            {
                title: "Restaurante O Cortiço",
                text: "Located in Ourém, O Cortiço is known for its regional dishes and welcoming atmosphere. Favorites include 'bacalhau com broa' and 'leitão assado'.",
                image: "/Bed.png",
                address: "Rua Dr. Francisco Sá Carneiro 5, 2490-480 Ourém",
            },
            {
                title: "O Barqueiro",
                text: "Set by the river in Foz do Alge, O Barqueiro specializes in freshwater fish dishes and offers a serene dining experience with picturesque views.",
                image: "/Bed.png",
                address: "Foz do Alge, 3260-423 Figueiró dos Vinhos",
            },
            {
                title: "Restaurante Tribeca",
                text: "Located in Serra d'El Rei, Tribeca offers a fusion of European cuisines in a stylish setting. The menu features dishes like duck confit and seafood risotto.",
                image: "/Bed.png",
                address: "Avenida da Serrana 5, 2525-802 Serra d'El Rei",
            },
            {
                title: "Restaurante Piadussa",
                text: "In the village of São Mamede, Piadussa serves traditional Portuguese meals in a rustic environment. Known for its 'bacalhau à Zé do Pipo' and homemade desserts.",
                image: "/Bed.png",
                address: "Rua da Pia do Urso 28, 2495-031 São Mamede",
            },
            {
                title: "Restaurante O Manito",
                text: "Situated in Almofala de Baixo, O Manito offers regional specialties like 'bacalhau à lagareiro' and 'cozido à portuguesa' in a welcoming atmosphere.",
                image: "/Bed.png",
                address:
                    "Zona Industrial de Almofala de Baixo, 3260-000 Figueiró dos Vinhos",
            },
            {
                title: "Restaurante A Lúria",
                text: "Located in Alcobaça, A Lúria combines traditional Portuguese flavors with modern culinary techniques. Signature dishes include octopus rice and roasted lamb.",
                image: "/Bed.png",
                address: "Rua Frei António Brandão 12, 2460-047 Alcobaça",
            },
            {
                title: "Restaurante O Cortiço",
                text: "In the town of Ourém, O Cortiço offers a menu rich in regional dishes, emphasizing local ingredients and traditional cooking methods.",
                image: "/Bed.png",
                address: "Rua Dr. Francisco Sá Carneiro 5, 2490-480 Ourém",
            },
            {
                title: "Restaurante O Manjar do Marquês",
                text: "Located in Pombal, O Manjar do Marquês is famous for its 'bacalhau à lagareiro' and extensive wine list, providing a refined dining experience.",
                image: "/Bed.png",
                address: "Avenida Heróis do Ultramar 185, 3100-462 Pombal",
            },
            {
                title: "Restaurante O Alcaide",
                text: "Set in the historic town of Óbidos, O Alcaide offers a romantic ambiance with a menu featuring traditional Portuguese dishes and fine wines.",
                image: "/Bed.png",
                address: "Rua Direita 60, 2510-001 Óbidos",
            },
            {
                title: "Restaurante O Casarão",
                text: "Situated in Batalha, O Casarão is known for its grilled meats and cozy atmosphere, making it a favorite among locals and tourists alike.",
                image: "/Bed.png",
                address: "Rua da Freiria 12, 2440-076 Batalha",
            },
            {
                title: "Restaurante O Cortiço",
                text: "In Ourém, O Cortiço offers a diverse menu with an emphasis on traditional flavors and a selection of regional wines.",
                image: "/Bed.png",
                address: "Rua Dr. Francisco Sá Carneiro 5, 2490-480 Ourém",
            },
        ],
    },
    {
        path: "trails",
        title: "Trails",
        description: "",
        img: "/Bed.png",
        content: [
            {
                title: "Burinhosa – Paredes de Vitória Trail",
                text: "A 11.6 km coastal trail starting in Burinhosa and leading to Paredes de Vitória beach. This route offers a mix of forest paths and seaside views, making it ideal for hiking and trail running.",
                image: "/Bed.png",
                address: "Burinhosa, Leiria, Portugal",
            },
            {
                title: "Moita – Burinhosa Trail",
                text: "A 21.9 km loop connecting Moita and Burinhosa through forested areas and rural landscapes. Suitable for both hiking and mountain biking enthusiasts.",
                image: "/Bed.png",
                address: "Moita, Leiria, Portugal",
            },
            {
                title: "Rota das Dunas",
                text: "A 81 km off-road trail that starts near São Pedro de Moel and extends inland. It features a mix of sandy paths, muddy sections, and technical terrains, perfect for mountain biking adventures.",
                image: "/Bed.png",
                address: "São Pedro de Moel, Leiria, Portugal",
            },
            {
                title: "Rota do Vale do Lapedo (PR1 LRA)",
                text: "A 4.5 km circular trail in Leiria that explores the Lapedo Valley, known for its archaeological significance. It's an easy hike suitable for families and history enthusiasts.",
                image: "/Bed.png",
                address: "Leiria, Portugal",
            },
            {
                title: "Rota da Lagoa de Óbidos (PR7 CLD)",
                text: "A 12.8 km circular trail around the Óbidos Lagoon, offering picturesque views of the lagoon and surrounding landscapes. Ideal for both hiking and cycling.",
                image: "/Bed.png",
                address: "Óbidos, Portugal",
            },
            {
                title: "Rota dos Moinhos (PR3 BTL)",
                text: "A 6.7 km trail in Batalha that takes you through historical water mills and lush greenery. It's a moderate hike that combines cultural heritage with natural beauty.",
                image: "/Bed.png",
                address: "Batalha, Portugal",
            },
            {
                title: "Rota do Carvão (PR6 PMS)",
                text: "An 11.3 km circular trail in Porto de Mós that traverses former coal mining areas, offering insights into the region's industrial past amidst scenic surroundings.",
                image: "/Bed.png",
                address: "Porto de Mós, Portugal",
            },
            {
                title: "Passadiços de Paredes da Vitória a Água de Madeiros",
                text: "An 8.7 km boardwalk trail connecting Paredes da Vitória and Água de Madeiros beaches. This easy route provides stunning coastal views and is suitable for all ages.",
                image: "/Bed.png",
                address: "Paredes da Vitória, Leiria, Portugal",
            },
            {
                title: "Rota do Peregrino (PR4 LRA)",
                text: "A 14.8 km trail starting in Leiria and ending in Fátima, following paths taken by pilgrims. It's a mix of paved and unpaved roads, offering a spiritual journey through diverse landscapes.",
                image: "/Bed.png",
                address: "Leiria to Fátima, Portugal",
            },
            {
                title: "Ecopista de Porto de Mós",
                text: "An 11 km eco-trail built on a former railway line in Porto de Mós. The path is mostly flat, making it perfect for leisurely walks, runs, and bike rides amidst nature.",
                image: "/Bed.png",
                address: "Porto de Mós, Portugal",
            },
        ],
    },
    {
        path: "cities",
        title: "Cities",
        description: "",
        img: "/Bed.png",
        content: [
            {
                title: "Leiria",
                text: "A dynamic city blending medieval charm with modern life. Known for its hilltop castle, the city also boasts museums, a historic center, lively cafes, and the scenic Lis River promenade.",
                image: "/Bed.png",
                address: "Leiria, Portugal",
            },
            {
                title: "Marinha Grande",
                text: "Portugal's glassmaking capital, known for its rich industrial history and the Glass Museum. Surrounded by the vast Leiria Pine Forest, it’s a cultural and nature-filled destination.",
                image: "/Bed.png",
                address: "Marinha Grande, Portugal",
            },
            {
                title: "Alcobaça",
                text: "Famous for its UNESCO World Heritage Monastery, Alcobaça is a historic city offering beautiful gardens, traditional pastry shops, and a peaceful cultural atmosphere.",
                image: "/Bed.png",
                address: "Alcobaça, Portugal",
            },
            {
                title: "Batalha",
                text: "Home to the monumental Batalha Monastery, a masterpiece of Gothic architecture. The city is small but culturally significant, with quaint streets and historical importance.",
                image: "/Bed.png",
                address: "Batalha, Portugal",
            },
            {
                title: "Caldas da Rainha",
                text: "A lively spa city founded by Queen Leonor, known for its thermal waters, daily fruit and vegetable market, and strong tradition in ceramics and arts.",
                image: "/Bed.png",
                address: "Caldas da Rainha, Portugal",
            },
            {
                title: "Fátima",
                text: "One of the world’s most important Catholic pilgrimage sites. Fátima offers spiritual depth, cultural museums, and serene parks surrounding the Sanctuary.",
                image: "/Bed.png",
                address: "Fátima, Portugal",
            },
            {
                title: "Nazaré",
                text: "A coastal city world-famous for its record-breaking waves and strong fishing traditions. It offers stunning ocean views, seafood cuisine, and vibrant local culture.",
                image: "/Bed.png",
                address: "Nazaré, Portugal",
            },
            {
                title: "Ourém",
                text: "A historic city featuring a medieval hilltop castle and old town, overlooking the modern part below. It’s closely linked to Fátima and offers a mix of history and tranquility.",
                image: "/Bed.png",
                address: "Ourém, Portugal",
            },
            {
                title: "Torres Novas",
                text: "A charming inland city known for its castle ruins, traditional architecture, and riverside gardens. Ideal for exploring local history and enjoying relaxed city life.",
                image: "/Bed.png",
                address: "Torres Novas, Portugal",
            },
            {
                title: "Rio Maior",
                text: "Known for its traditional salt pans and the nearby Serra de Aire e Candeeiros Natural Park. A great base for exploring nature and local gastronomy.",
                image: "/Bed.png",
                address: "Rio Maior, Portugal",
            },
            {
                title: "Peniche",
                text: "A vibrant coastal city and surfing hotspot, also home to historic fortresses and the Berlengas Nature Reserve. Offers boat trips, fresh seafood, and cultural landmarks.",
                image: "/Bed.png",
                address: "Peniche, Portugal",
            },
            {
                title: "Pombal",
                text: "Strategically located between Lisbon and Porto, this city features a medieval castle and is rich in historical ties to the Marquis of Pombal, with a calm and cultural vibe.",
                image: "/Bed.png",
                address: "Pombal, Portugal",
            },
            {
                title: "Bombarral",
                text: "A wine-producing city surrounded by vineyards and close to the famous Buddha Eden Garden. Combines rural charm with cultural attractions and local flavors.",
                image: "/Bed.png",
                address: "Bombarral, Portugal",
            },
        ],
    },
];

/*
THEMEPLATE

{
        path: "art-culture",
        title: "Art & Culture",
        content: [
            {
                title: "Castelo de Leiria",
                text: " A medieval castle perched atop a hill, offering panoramic views of Leiria. It showcases various architectural styles and hosts cultural events throughout the year.",
                image: "/Bed.png",
                address: "Rua do Castelo, 2400-235 Leiria",
                website: "https://www.visiteleiria.pt/",
            },
        ],
    },



*/

export default around;
